---
port_profiles:
  - profile: Tenant_A_pod1_clientA
    mode: access
    vlans: '40'
  - profile: Tenant_A_pod1_clientB
    mode: access
    vlans: '40'
  - profile: Tenant_A_pod2_clientA
    mode: access
    vlans: '34'

servers:
  - name: server01
    rack: rack01
    adapters:
      - endpoint_ports:
          - Eth1

        switch_ports:
          - Ethernet4
        switches:
          - DC1_LEAF1A
        profile: Tenant_A_pod1_clientA
        spanning_tree_portfast: edge
  - name: server02
    rack: rack01
    adapters:
      - endpoint_ports:
          - Eth1

        switch_ports:
          - Ethernet4

        switches:
          - DC1_LEAF2A

        profile: Tenant_A_pod1_clientB
        spanning_tree_portfast: edge

  - name: server03
    rack: rack02
    adapters:
      - endpoint_ports:
          - Eth1

        switch_ports:
          - Ethernet4

        switches:
          - DC1_LEAF3A

        profile: Tenant_A_pod2_clientA
        spanning_tree_portfast: edge


